name: Check Suite

on:
  check_run:

permissions:
  contents: read

jobs:
  echo:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo
        env:
          CONTEXT: ${{ toJson(github) }}
        run: echo "$CONTEXT"
