name: Test

on:
  workflow_dispatch:

env:
  YES: "YES"

jobs:
  echo:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Echo
        run: echo "$YES"
      - name: Echo 2
        run: echo "${{ env.YES }}"
