name: Update Antora UI

on:
  workflow_dispatch:

permissions: write-all

jobs:
  update:
    name: Build
    uses: spring-io/spring-security-release-tools/.github/workflows/update-antora-ui-spring.yml@9d0e98600ea8ff2814e43aa984f7f9f6faf6a593
    with:
      docs-branch: 'main'
    secrets: inherit
