name: Update Antora UI Spring

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  update-antora-ui-spring:
    runs-on: ubuntu-latest
    name: Update Antora UI Spring
    steps:
      - uses: actions/checkout@v4
      - uses: ./update-antora-ui-spring-action
        with:
          docs-branch: 'main'
          token: ${{ secrets.GITHUB_TOKEN }}
